### ISSUE TITLE
make: *** No rule to make target `../reg_defines.h ', needed by` src / org / netfpga / backend / NFDeviceConsts.java'. Stop.

### ISSUE THREAD

**Issue by rjacauna** [cmlab/NetFPGA-1G-CML#15]
Hi all,
Someone had already got the bug down and managed to solve?
I've done the pass-by-step instructions for creating lite switch records, but this error remains.
If anyone can and know how to solve, please give feedback.
Thank you!

make: **\* No rule to make target `../reg_defines.h ', needed by` src / org / netfpga / backend / NFDeviceConsts.java'. Stop.

**Comment by davidva-cml** [comment]
Hello,

Are you trying to build the router GUI?  If so, please perform the 
following steps:
1.  Run "make regs" from projects/reference_router_nf1_cml/hw/
2.  Run "make" from projects/reference_router_nf1_cml/sw/host/gui (check 
   first that reg_defines.h exists in 
   projects/reference_router_nf1_cml/sw/host/ from Step 1)

David Van Arnem
Development Engineer
Computer Measurement Laboratory

**Comment by rjacauna** [comment]
Sucesso! Ifs running.
Thais for all.
Rafael

Em quinta-feira, 13 de agosto de 2015, david00 notifications@github.com
escreveu:

> Hello,
> 
> Are you trying to build the router GUI? If so, please perform the
> following steps:
> 1. Run "make regs" from projects/reference_router_nf1_cml/hw/
> 2. Run "make" from projects/reference_router_nf1_cml/sw/host/gui (check
>    first that reg_defines.h exists in
>    projects/reference_router_nf1_cml/sw/host/ from Step 1)
> 
> David Van Arnem
> Development Engineer
> Computer Measurement Laboratory
> 
> On 08/11/2015 07:21 PM, Rafael Jacaúna wrote:
> 
> > Hi all,
> > Someone had already got the bug down and managed to solve?
> > I've done the pass-by-step instructions for creating lite switch
> > records, but this error remains.
> > If anyone can and know how to solve, please give feedback.
> > Thank you!
> > 
> > make: **\* No rule to make target |../reg_defines.h ', needed by| src /
> > org / netfpga / backend / NFDeviceConsts.java'. Stop.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cmlab/NetFPGA-1G-CML/issues/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cmlab/NetFPGA-1G-CML/issues/15#issuecomment-130762832
> .

## 

Enviado do Gmail para iPad

**Comment by rjacauna** [comment]
Guys,
Someone already had the experience of getting synthesize the project "
reference_nic_nfl_cml" without error, but when you run the loopback test it is
not completed successfully?
Another point: although I can configure IP interfaces, to connect a station
in one of the doors, and setting it on the same network, do not get success
in the ICMP test.
I am unsure what to do!
I am looking forward to some light at the end of the tunnel !!! ;-)
Regards,
Rafael Jacaúna

2015-08-14 14:57 GMT-03:00 david00 notifications@github.com:

> Closed #15 https://github.com/cmlab/NetFPGA-1G-CML/issues/15.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cmlab/NetFPGA-1G-CML/issues/15#event-382828214.

## 

Atenciosamente,
Rafael Jacaúna

**Comment by rjacauna** [comment]
Olá, Eliane,,

Você recebeu um convite de Rafael para se inscrever no Campeonato Universitário do Dropbox! No Campeonato Universitário, você e seus colegas se juntam para ganhar até 25 GB de espaço gratuito no Dropbox por dois anos!

Para ganhar espaço, convide amigos e use o Dropbox para compartilhar arquivos, trabalhar em equipe e cuidar de projetos.

Entre no Campeonato Universitário![2]

Observe que, para participar, é preciso ser um aluno atualmente matriculado em uma instituição de ensino superior. Saiba mais sobre o Campeonato Universitário.[3]

Divirta-se com o Dropbox!


 
 Trabalhe em equipe, ganhe em equipe.

____________________________________________________
Se preferir não receber convites do Dropbox, acesse esta página[42].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/1pwgsesaG7PANqBwCZve2A/campuscup?text=1
[2]: https://www.dropbox.com/l/jmEoce9tK9bP7XvamMtafs/campuscup?text=1
[3]: https://www.dropbox.com/l/EjvwqpEpNgv3stqO5zr6sk/help/9131?text=1
[4]: https://www.dropbox.com/l/ifpxBalG1ZAmtUGSScyiPH?text=1

**Comment by rjacauna** [comment]
Olá, William,,

Você recebeu um convite de Rafael para se inscrever no Campeonato Universitário do Dropbox! No Campeonato Universitário, você e seus colegas se juntam para ganhar até 25 GB de espaço gratuito no Dropbox por dois anos!

Para ganhar espaço, convide amigos e use o Dropbox para compartilhar arquivos, trabalhar em equipe e cuidar de projetos.

Entre no Campeonato Universitário![2]

Observe que, para participar, é preciso ser um aluno atualmente matriculado em uma instituição de ensino superior. Saiba mais sobre o Campeonato Universitário.[3]

Divirta-se com o Dropbox!


 
 Trabalhe em equipe, ganhe em equipe.

____________________________________________________
Se preferir não receber convites do Dropbox, acesse esta página[42].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/A5lKQtXIOIPAnYTZTZq02B/campuscup?text=1
[2]: https://www.dropbox.com/l/bxRB2n0sLfhPHuODDMoWet/campuscup?text=1
[3]: https://www.dropbox.com/l/lbaTQykVDep321JhnzmSrl/help/9131?text=1
[4]: https://www.dropbox.com/l/aNB4BQr8Y6Fm3sZladt4PI?text=1
