### ISSUE TITLE
Java GUI make

### ISSUE THREAD

**Issue by eselahe** [cmlab/NetFPGA-1G-CML#6]
Hi all,
I want to use java GUI for reference_router_nf1_cml. I follow the directions in below page to build the GUI:
https://github.com/NetFPGA/NetFPGA-public/wiki/NetFPGA-10G-Reference-Router
But when I run "make" in this path:
NetFPGA-10G-live/projects/reference_router_nf1_cml/sw/host/gui
I get:
[root@localhost gui]# make
make[1]: Entering directory `/home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/sw/host/common'
gcc -fpic -c nf10util.c nf_util.c
gcc -shared nf10util.o nf_util.o -o libnf10.so
make[1]: Leaving directory`/home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/sw/host/common'
make: **\* No rule to make target `../reg_defines.h', needed by`src/org/netfpga/backend/NFDeviceConsts.java'.  Stop.

How can I make Java GUI, correctly?

Thanks.

**Comment by davidva-cml** [comment]
Hello,

The router (and all the CML projects except the NIC) have a register 
infrastructure that the host software uses to communicate with the 
design.  The register infrastructure can be built by entering the "hw" 
directory in the design and running "make regs."  This command will 
create the "reg_defines.h" file that is missing and causing the gui 
build to fail.

Thanks,
David

**Comment by eselahe** [comment]
The register infrastructure didn't built by entering the "hw"
directory in the design and running "make regs." I get these errors:

[root@localhost hw]# make regs
Makefile:43: system_incl.make: No such file or directory
echo exit|xps -nw system.xmp

Xilinx Platform Studio
Xilinx EDK 14.6 Build EDK_P.68d
Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

XPS% Loading xmp file system.xmp
ERROR:EDK - IPNAME: bram_block, INSTANCE: microblaze_0_bram_block -
   BUS_INTERFACE PORTA not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 136 
ERROR:EDK - IPNAME: bram_block, INSTANCE: microblaze_0_bram_block -
   BUS_INTERFACE PORTB not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 137 
ERROR:EDK - IPNAME: axi_interconnect, INSTANCE: axi_interconnect_0 - PORT
   interconnect_aclk not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 242 
ERROR:EDK - IPNAME: axi_interconnect, INSTANCE: axi_interconnect_0 - PORT
   INTERCONNECT_ARESETN not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 243 
ERROR:EDK - IPNAME: axi_interconnect, INSTANCE: axi_interconnect_0 - PARAMETER
   C_INTERCONNECT_CONNECTIVITY_MODE not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 241 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - BUS_INTERFACE S_AXI
   not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 255 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PORT S_AXI_ACLK not
   found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 256 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PORT TX not found in
   the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 257 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PORT RX not found in
   the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 258 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PORT Interrupt not
   found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 259 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PARAMETER C_BAUDRATE
   not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 249 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PARAMETER C_DATA_BITS
   not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 250 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PARAMETER
   C_USE_PARITY not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 251 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PARAMETER
   C_ODD_PARITY not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 252 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PARAMETER C_BASEADDR
   not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 253 
ERROR:EDK - IPNAME: axi_uartlite, INSTANCE: RS232_Uart_1 - PARAMETER C_HIGHADDR
   not found in the MPD -
   /home/karin/NetFPGA-10G-live/projects/reference_router_nf1_cml/hw/system.mhs
   line 254 
ERROR:EDK - while loading XMP file

XPS% psf2Edward -inp .xmp -exit_on_error -edwver 1.2 -xml /.xml 
Release 14.6 - psf2Edward EDK_P.68d (lin64)
Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
WARNING:UtilitiesC:159 - Message file "usenglish/EDK.msg" wasn't found.
ERROR:EDK - Could not open input file .xmp.
ERROR:EDK - psf2Edward initialization failed
make: **\* [regs] Error 8
