### ISSUE TITLE
SCONE make

### ISSUE THREAD

**Issue by eselahe** [cmlab/NetFPGA-1G-CML#7]
Hi everyone,
I have programmed my NetFPGA with reference_router_nf1_cml project. when I want to make scone I get below error:

[root@localhost scone]# make
gcc -c -g -Wall -D_DEBUG_ -D_LINUX_ -I lwtcp -I ../common -D_GNU_SOURCE -D_CPUMODE_ sr_main.c -o sr_main.o
gcc -c -g -Wall -D_DEBUG_ -D_LINUX_ -I lwtcp -I ../common -D_GNU_SOURCE -D_CPUMODE_ sr_base.c -o sr_base.o
In file included from lwtcp/lwip/tcp.h:43:0,
                 from sr_base.c:49:
lwtcp/lwip/ip.h:90:10: warning: ‘packed’ attribute ignored for field of type ‘struct ip_addr’ [-Wattributes]
   PACK_STRUCT_FIELD(struct ip_addr src);
          ^
lwtcp/lwip/ip.h:91:10: warning: ‘packed’ attribute ignored for field of type ‘struct ip_addr’ [-Wattributes]
   PACK_STRUCT_FIELD(struct ip_addr dest);
          ^
sr_base.c: In function ‘sr_init_low_level_subystem’:
sr_base.c:189:5: warning: implicit declaration of function ‘init_ospf’ [-Wimplicit-function-declaration]
     init_ospf(sr);
     ^
sr_base.c:91:14: warning: variable ‘topo’ set but not used [-Wunused-but-set-variable]
     uint16_t topo =  0;
              ^
sr_base.c:90:14: warning: variable ‘port’ set but not used [-Wunused-but-set-variable]
     uint16_t port =  12345;
              ^
sr_base.c:88:11: warning: variable ‘server’ set but not used [-Wunused-but-set-variable]
     char  _server = "171.67.71.18";
           ^
sr_base.c:86:11: warning: variable ‘host’ set but not used [-Wunused-but-set-variable]
     char  *host   = "vrhost";
           ^
gcc -c -g -Wall -D_DEBUG_ -D_LINUX_ -I lwtcp -I ../common -D_GNU_SOURCE -D_CPUMODE_ sr_dumper.c -o sr_dumper.o
In file included from sr_dumper.c:7:0:
sr_dumper.h:16:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
make: *_\* [sr_dumper.o] Error 1

How do I fix this problem?

Thanks,
elahe

**Comment by davidva-cml** [comment]
Hello,

To get the pcap.h and libnet.h header files needed for SCONE, please 
install the packages "libpcap-devel" and "libnet-devel" from Fedora's 
package repositories using yum.

Thanks,
David
