### ISSUE TITLE
Is there anyone to let me access the repository?

### ISSUE THREAD

**Issue by rohnugu** [cmlab/NetFPGA-1G-CML#9]
Hello, I recently bought 2 NetFPGA-1G-CML for my research,
but currently I have no access grant for the NetFPGA-1G-CML-live (?) repository. 
I've sent mails for registration twice but it seems that there is no response. 
So please let me know how can I access the repository.

Thanks.

**Comment by arashkh** [comment]
Hi,
I'm having the same problem. Looks like the reference projects for
NetFPGA-1G and NetFPGA-10G are not suitable for use with the NetFPGA-1G-CML
so access to the repository is necessary. Does anyone have access to that
repository?

**Comment by mwlaverty** [comment]
Typically, your registration request should be granted within a few hours, but allow 3 to 5 USA business days to process your request in case there is a delay.

**Comment by prakashganesh** [comment]
Hello i had waited for more than 1 month but still not yet got
